"notificationLevel": 0,
"notificationTitle": "消息推送更新",
"targetUserId": 2014,
"invalidatedTime": 1640793600000,
"notificationType": "1",
"notificationContent": "系统消息推送功能更新",
"createTime": 1638240119000,
"id": 42,
"sourceUserId": 0,
"serviceId": 6,

"readedNum": 0,
"deletedNum": 0,
"pulledOut": 0,